sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t erikdevries/rpi-couchpotato .
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    TAG=latest
    docker tag erikdevries/rpi-couchpotato erikdevries/rpi-couchpotato:$TAG
    docker push erikdevries/rpi-couchpotato:$TAG
    docker push erikdevries/rpi-couchpotato
  fi
