sudo: required

services:
- docker

language: bash

branches:
  only:
  - master

script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t erikdevries/rpi-couchpotato .
# run and test image
- docker run -p 5050:5050 -d erikdevries/rpi-couchpotato
- curl -vsf 'http://localhost:5050' &> /dev/stdout

after_success:
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    docker tag erikdevries/rpi-couchpotato erikdevries/rpi-couchpotato:latest
    docker push erikdevries/rpi-couchpotato
  fi
